- src/components/Editor/PenHeader.vue
- src/components/Editor/penSetting.vue
- src/stores/workStore.js
- src/views/Pen.vue
pen header independent
=>Editor/PenHeader.vue
> [refactor] pen header independent

- src/components/Editor/PenHeader.vue
- src/stores/workStore.js
- src/views/Pen.vue
> [fix]penheader change view fixed

- src/router/index.js
- src/stores/useAuthStore.js
修復前面兩隻pr發生的bug
預先寫好的路由守衛無法正常使用 現在修復
登入以後不能進入signup login page
> [fix]調整路由守衛

- src/components/SubHeader.vue
- src/views/YourWork.vue
使用者頭像下拉選單裡的Your Work, Profile, New Pen到正確的連結
> [feat] 使用者頭像下拉選單裡的Your Work, Profile, New Pen到正確的連結

- src/App.vue
- src/stores/useAuthStore.js
- src/views/Login.vue
- src/views/SettingProfile.vue
重整時透過onMounted將資料寫入欄位裡
狀態儲存裡面新增userProfile變數儲存了使用者儲存在後端的資料
可以透過
```
import { useAuthStore } from "@/stores/useAuthStore";
const authStore = useAuthStore();
authStore.userProfile 
authStore.userProfile.username
```
取用 >使用動態路由:username :id e.t.c
側邊攔的呼叫後端api
可以查詢如何使用
closes #15  
closes #13 
closes #53 
備註
使用了統一的空格設定 第一次會在追蹤一次 之後此問題會排除
大頭貼上傳以後如果檔案太大會有錯誤
新增一張票 使用者上傳大頭貼以後可再次裁切 編輯? #62
> [feat]加入使用者更新資料功能

- src/components/PenCardLayout.vue
- src/views/Following.vue
- src/views/Search.vue
- src/views/Trending.vue
修trending頁跟following頁 的pencard bug
順便把search頁導入作品卡
> [fix] Trending頁 與 Following頁 props 參數錯誤 [feat] 搜尋頁導入作品卡

- src/views/Following.vue
- src/views/Trending.vue
> [fix] 暫時把Trending.vue 與 Following.vue 的PenCard路徑改成PenCardTemp

- src/components/PenCardTemp.vue
- src/views/Pen.vue
修改iframe preview url
**要在client的.env裡加入 VITE_URL_BASE=http://localhost:5173**
在trending頁會報錯是因為傳入的id不是integer
close #81
> [fix] edit pen card iframe preview url

- src/components/Editor/Editor.vue
- src/views/Pen.vue
修改 editor RWD 樣式
header RWD 樣式會另外開issue修
close #8
> [style] update editor RWD styles

- src/components/Editor/PenSettingModal.vue
- src/stores/workStore.js
- src/views/Trending.vue
刪除PenCard不需要用到的store import
Editor Setting 修正變數名稱(isAutoSave / isAutoPreview)
close #102
> [refactor]刪除不需要用到的store import 以及 [fix]Editor Setting 修正變數名稱

- src/components/Editor/PenHeader.vue
- src/stores/workStore.js
- src/views/Pen.vue
移動至垃圾桶
is_trash = true (狀態名稱待修改)
從垃圾桶刪除
is_deleted = true (狀態名稱待修改)
從資料庫移除
目前尚未串接
新增刪除提示
close #97
> [feat]前端 API 新增/修改/移至垃圾桶/從垃圾桶移除 完成 

- src/views/Following.vue
- 串接後端 `/api/following/pens API`
- 切換頁面時，自動載入下一頁資料
- 若使用者沒有追蹤任何人則顯示未追蹤訊息
https://github.com/user-attachments/assets/70090b9c-5909-47be-b1f5-52a23b12e748
登入後Header沒有正確切換成登入後樣式
> [feat] Following頁 API串接與預載功能完成

- src/components/Editor/PenSettingModal.vue
- src/stores/workStore.js
> [feat] pen tag功能完成/回傳文字改為英文/加入 try & catch

- src/components/Editor/PenHeader.vue
- src/components/Editor/PenSettingModal.vue
- src/components/Editor/ProTag.vue
- src/stores/useWorkStore.js
- src/views/Pen.vue
editor編輯器根據作品設定以及用戶是否為Pro會員 改變 isPrivate 設定
非pro會員
pro會員
close #106
> [feat] editor編輯器串 Private 功能

- src/components/PenCardRow.vue
- src/components/PenCardTemp.vue
- src/components/ViewModeChange.vue
- src/views/SettingProfile.vue
- src/views/YourWork.vue
> [Refactor]將切換顯示ui拿出來做成元件

- src/components/Editor/EditorPreview.vue
- src/stores/useWorkStore.js
修改 iframe HTML 檔案處理方式 讓 js 可以使用import 以及 操控DOM元素
close #139
> [fix] js 無法抓取 Dom 元件

- src/router/index.js
- src/views/Login.vue
close #110
- 新增 `meta.requiresAuth` 到 
`/your-work`、`/following`、`/settings/profile`、`/settings/account`
- 未登入者訪問受限頁面會被導向 `/login`
> [feat] Setting, Trending, Following 頁面加上路由守衛

- src/components/Editor/EditorPreview.vue
- src/components/Editor/PenHeader.vue
- src/components/Editor/PenSettingModal.vue
- src/stores/useWorkStore.js
- src/views/Pen.vue
修正用 Editor 右上按鈕開啟 Setting 不會自動切換 tab 分頁
close #157 
full page mode preview 拿掉 debounce
close #161 
View Mode 選單改扁一點
close #162
> [fix] 修正用 Editor 右上按鈕開啟 Setting 不會自動切換 tab 分頁 [refactor] full page mode preview 拿掉 debounce [style] View Mode 選單改扁一點

- src/components/Editor/AnonLoginModal.vue
- src/components/Editor/Editor.vue
- src/components/Editor/PenHeader.vue
- src/components/PenDetails/PenContent.vue
- src/components/PenDetails/PenTimeStamp.vue
- src/components/ViewModeChange.vue
修正 Save 按鈕在新作品儲存之後會消失的問題
刪除defineEmits defineProps import 
close #173
> [fix] 修正 Save 按鈕在新作品儲存之後會消失的問題

- src/components/Editor/AnonLoginModal.vue
- src/views/Pen.vue
在editor 按 ctrl + s / command + s 能夠直接儲存
在登入、註冊視窗按enter可以直接送出表單
> Issue/164 Editor 快捷鍵儲存

- src/views/Pen.vue
在pen.vue  watch 作品有無id
有id => autosave
無id => return
> [fix] 作品尚未建立時沒有 autosave

- src/components/PenCardLayout.vue
- src/components/PenCardRow.vue
close #172 
範例影片
https://github.com/user-attachments/assets/1149aab1-b470-4495-ac68-81e6748a3ff0
> [feat] 作品表格式排版樣式與RWD

- src/router/index.js
- src/views/UsersCaines.vue
> [refactor]修正 UsersCaines.vue 中的條件判斷，確保在顯示用戶名時檢查 authStore.userProfile

- src/components/Editor/Cdnjs.vue
- src/components/Editor/PenHeader.vue
- src/components/Editor/PenSettingModal.vue
- src/components/UserMenu.vue
> [feat] editor CDNJS search 功能完成 樣式待修改

- src/components/Editor/DoseFooter.vue
- src/views/Pen.vue
> [refactor] DoseFooter 做成獨立元件/ 加入comment 按鈕

- src/components/PenCards/PenCard.vue
- src/layouts/ProfileLayout.vue
- src/layouts/SettingLayout.vue
- src/views/Login.vue
- src/views/SettingAccount.vue
- src/views/UsersFollowers.vue
- src/views/UsersFollowing.vue
> [Fix]調整使用者檢查追蹤bug

- src/components/Editor/DoseFooter.vue
- src/components/Editor/PenHeader.vue
- src/views/Pen.vue
PenHeader LOGO 更新
DoseFooter comment button 位置調整
close #238
> [fix] 未登入開啟新Dose會顯示錯誤 已修正

- src/components/MainSidebar.vue
- src/components/SubFooter.vue
- src/components/SubHeader.vue
修改 sidebar 開啟 dose 按鈕顯示文字 以及修正手機版路由及其顯示文字
> [fix] 把 pen 和 caine 更名為 dose 

- src/components/Editor/Cdnjs.vue
- src/components/Editor/PenHeader.vue
- src/components/Editor/PenSettingModal.vue
- src/components/Editor/SettingCard.vue
- src/components/Editor/SettingInput.vue
- src/components/Editor/SettingSelect.vue
- src/components/Editor/SettingTagInput.vue
- src/components/Editor/SettingTextarea.vue
- src/components/icons/TrashCanIcon.vue
將 Modal 內 SettingCard 拉出來做成 Vue 元件
垃圾桶圖示新增 fill="currentColor"
close #258
> [refactor] DoseSettingModal 程式碼整理

- package-lock.json
- package.json
- src/components/Notify.vue
- src/components/PenCards/PenCard.vue
- src/utils/notify.js
- src/views/Notifications.vue
本次pr 需要npm i
@vueuse/core新增套件
來達成 通知選單再點擊區域外 可以關閉選單
https://github.com/user-attachments/assets/6d2ba248-b6c0-4ede-b019-a62147fa795c
後端pr https://github.com/CodecaineWebsite/Codecaine_server/pull/99
closes #262
> [Feat]通知延伸功能

- src/components/Editor/DoseFooter.vue
- src/components/Editor/PenHeader.vue
- src/stores/useWorkStore.js
> [fix]開啟別人作品時 delete按鈕不出現

- src/stores/useWorkStore.js
> [fix] 如果沒有改 title 預設為 untitled

- src/components/PenCards/PenCard.vue
- src/views/Loved.vue
- src/views/Private.vue
- src/views/Public.vue
loved頁面的api路徑錯誤了 所以會取得錯誤的資料 
在此pr修復
> [fix]修復錯誤api路徑

- src/components/Editor/PenSettingModal.vue
> [feat]新增 CDNjs 查詢功能

- src/components/Editor/EditorPreview.vue
- src/components/PenCards/PenCard.vue
- src/views/Pen.vue
作品未儲存也可以預覽
PenCard 預覽畫面關閉scroll功能
close #292
> [fix] 修正作品儲存後才能預覽畫面

- src/components/PenDetails/PenDetailModal.vue
- src/components/PenDetails/PenDetailModalHeader.vue
> [fix] PenDetailModalHeader 補上 favoriteStore 變數, 刪除開發用console.log

- src/components/MainSidebar.vue
- src/components/SubHeader.vue
> 調整 sidebar 字體大小及粗細

- src/layouts/MainLayout.vue
- src/views/Showcase.vue
> [fix] MainLayout overflow 改 hidden, Show case 頁 Caines 改成 doses

- src/components/FollowBtn.vue
- src/components/icons/Add.vue
- src/index.css
> [style] 修改Follow Btn樣式

- src/components/Editor/ProTag.vue
- src/components/PenCards/PenCard.vue
- src/components/PenDetails/PenDetailModalHeader.vue
- src/components/SubHeader.vue
> [fix]ProTag引入PenDetaleModal

- src/components/FollowBtn.vue
- src/components/Notify.vue
- src/components/PenCards/PenCard.vue
- src/components/UserMenu.vue
- src/views/Login.vue
> [fix]通知選單RWD

- src/components/Comments/CommentCard.vue
- src/components/Comments/CommentForm.vue
- src/components/DeletedPenCard.vue
- src/components/PenCards/PenCardDropdown.vue
- src/components/PenCards/PenCommentButton.vue
- src/components/PenCards/PenDetailsButton.vue
- src/components/PenCards/PenViewButton.vue
- src/components/SubHeader.vue
- src/components/UserMenu.vue
- src/components/ViewModeChange.vue
- src/views/Following.vue
- src/views/YourWork.vue
> [fix]把游標樣式加進來

- src/views/Pen.vue
> [feat] 在未儲存的時候 關閉編輯器畫面會跳確認訊息

- src/components/Editor/PenHeader.vue
- src/components/Editor/ProTag.vue
- src/components/Notify.vue
- src/components/PenCards/PenCard.vue
- src/components/SubHeader.vue
- src/components/UserMenu.vue
- src/components/icons/SidebarToggleIcon.vue
- src/layouts/ProfileLayout.vue
> [fix] SubHeader 下拉選單按鈕再次按下可以關閉選單

- src/components/Editor/Cdnjs.vue
> [fix] CDNjs Search debounce修改
